module.exports = {
  SECRET_KEY:
    "eyJ0aW1lIjoiVHVlIE5vdiAyOSAyMDIyIDE3OjQ1OjUzIEdNVCswNTMwIChJbmRpYSBTdGFuZGFyZCBUaW1lKSIsInVzZXJJZCI6MTIsImlhdCI6MTY2OTcyNDE1M30.UZuqiFBJMQ9ndKjwf1DelrCwtpxWhxD0Va5PZTEBMTI",
};
